version: 2
jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-v1-{{ checksum "./yarn.lock" }}
      - run:
          name: install-yarn packages
          command: yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-v1-{{ checksum "./yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Deploy
          command: yarn deploy
      
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
