name: Deploy helpers

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Prepare Node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: '12.x'
    
    
    - name: Install packages
      run: yarn install
      
      
    - name: Deploy Lambdas 
      run: yarn deploy